env:
  FORCE_COLOR: 1

freebsd_task:
  freebsd_instance:
    matrix:
      - image_family: freebsd-12-3
      - image_family: freebsd-13-0
  install_script: pkg install -y dash bash zsh ksh93 mksh oksh
  prepare_script:
    - ./shellspec --task fixture:stat:prepare
  script:
    - contrib/all.sh contrib/various_test.sh
