language: shell
os: linux
dist: bionic
addons:
  apt:
    update: true
jobs:
  include:
    - os: osx # macOS 10.10 Yosemite 2014-06
      osx_image: xcode6.4
      env: SHELLS="sh bash zsh ksh"
    - os: osx # macOS 10.11 El Capitan 2015-06
      osx_image: xcode8
      env: SHELLS="sh bash zsh ksh"
    - os: osx # macOS 10.12 Sierra 2016-06
      osx_image: xcode9.2
      env: SHELLS="sh bash zsh ksh"
    - os: osx # macOS 10.13 High Sierra 2017-06
      osx_image: xcode10.1
      env: SHELLS="sh bash zsh ksh"
    - os: osx # macOS 10.14 Mojave 2018-06
      osx_image: xcode10.2
      env: SHELLS="sh bash zsh ksh"
before_script:
  - ./shellspec --shell sh --task fixture:stat:prepare
script:
  - contrib/all.sh contrib/various_test.sh
