version: 2.1

# Define the executor type
executors:
  macos1013:
    macos:
      xcode: 10.1.0 # 10.13.6
  macos1014:
    macos:
      xcode: 11.1.0 # 10.14.4
  macos1015:
    macos:
      xcode: 12.4.0 # 10.15.5

jobs:
  lint:
    docker:
      - image: koalaman/shellcheck-alpine:v0.7.1
    steps:
      - checkout
      - run: shellcheck shellspec $(find lib libexec spec examples -name '*.sh')
  report:
    working_directory: ~/shellspec
    docker:
      - image: alpine
    steps:
      - run: apk add --no-progress --no-cache ca-certificates
      - checkout
      - run: ./shellspec --task fixture:stat:prepare
      - run: ./shellspec -o tap -o junit
      - run:
          command: |
            mkdir -p ~/report/shellspec
            cp report/results_junit.xml ~/report/shellspec/
          when: always
      - store_test_results:
          path: ~/report
      - store_artifacts:
          path: report
  coverage:
    working_directory: ~/shellspec
    docker:
      - image: shellspec/kcov
    steps:
      - checkout
      - run: ./shellspec --task fixture:stat:prepare
      - run: ./shellspec --kcov
      - store_artifacts:
          path: coverage
  test:
    # Using parameters
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - run: ./shellspec --shell sh --task fixture:stat:prepare
      - run: contrib/all.sh contrib/various_test.sh

workflows:
  lint_report_coverage:
    jobs:
      - lint
      - report
      - coverage:
          requires:
            - lint
            - report
  daily_update_schedule:
    jobs:
      - lint
      - coverage:
          requires:
            - lint
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              os: [macos1013, macos1014, macos1015]
